// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZDjNubkjZu4Lzhu-Pl25zM_EiRuLBzHw',
    appId: '1:1075161631917:web:4c496f2ad822bff4030a24',
    messagingSenderId: '1075161631917',
    projectId: 'questionapp-a3d85',
    authDomain: 'questionapp-a3d85.firebaseapp.com',
    storageBucket: 'questionapp-a3d85.firebasestorage.app',
    measurementId: 'G-04ETDV2Z9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfYazqEzNCvvGeDt-KSOg8yifrGppBG4k',
    appId: '1:1075161631917:android:0a8c36350924af6e030a24',
    messagingSenderId: '1075161631917',
    projectId: 'questionapp-a3d85',
    storageBucket: 'questionapp-a3d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOd6JwGe6csXfiXiKWVRYrcHtVEEfUsmk',
    appId: '1:1075161631917:ios:730cd820426367b7030a24',
    messagingSenderId: '1075161631917',
    projectId: 'questionapp-a3d85',
    storageBucket: 'questionapp-a3d85.firebasestorage.app',
    androidClientId:
        '1075161631917-tbkvuvue4hlimsb0h65mkh9khfqsnjvq.apps.googleusercontent.com',
    iosClientId:
        '1075161631917-d5npdk2m3mu2klt1pb4vflsue4hnagu5.apps.googleusercontent.com',
    iosBundleId: 'com.devansh.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOd6JwGe6csXfiXiKWVRYrcHtVEEfUsmk',
    appId: '1:1075161631917:ios:730cd820426367b7030a24',
    messagingSenderId: '1075161631917',
    projectId: 'questionapp-a3d85',
    storageBucket: 'questionapp-a3d85.firebasestorage.app',
    androidClientId:
        '1075161631917-tbkvuvue4hlimsb0h65mkh9khfqsnjvq.apps.googleusercontent.com',
    iosClientId:
        '1075161631917-d5npdk2m3mu2klt1pb4vflsue4hnagu5.apps.googleusercontent.com',
    iosBundleId: 'com.devansh.chit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZDjNubkjZu4Lzhu-Pl25zM_EiRuLBzHw',
    appId: '1:1075161631917:web:b88e9f23d7f5a708030a24',
    messagingSenderId: '1075161631917',
    projectId: 'questionapp-a3d85',
    authDomain: 'questionapp-a3d85.firebaseapp.com',
    storageBucket: 'questionapp-a3d85.firebasestorage.app',
    measurementId: 'G-16X6VMVCS2',
  );
}
